-- CreateEnum
CREATE TYPE "MockupKind" AS ENUM ('PRINT', 'AI');

-- AlterTable
ALTER TABLE "BuildDraft" ADD COLUMN     "printMockupFingerprint" TEXT,
ADD COLUMN     "printMockupGeneratedAt" TIMESTAMP(3),
ADD COLUMN     "printMockupId" TEXT;

-- AlterTable
ALTER TABLE "Mockup" ADD COLUMN     "height" INTEGER,
ADD COLUMN     "kind" "MockupKind" NOT NULL DEFAULT 'AI',
ADD COLUMN     "parentId" TEXT,
ADD COLUMN     "width" INTEGER;

-- CreateIndex
CREATE INDEX "Mockup_kind_idx" ON "Mockup"("kind");

-- AddForeignKey
ALTER TABLE "BuildDraft" ADD CONSTRAINT "BuildDraft_printMockupId_fkey" FOREIGN KEY ("printMockupId") REFERENCES "Mockup"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Backfill: existing rows were generated by Gemini (AI mockups).
-- The default 'AI' already covers them; explicitly mark any print-sentinel
-- rows (written during the transitional Commit 4) as PRINT and remap the
-- BuildDraft link from aiMockupId -> printMockupId so no print mockup
-- remains coupled to the AI column.
UPDATE "Mockup" SET "kind" = 'PRINT' WHERE "model" = 'print';

UPDATE "BuildDraft"
SET
  "printMockupId" = "aiMockupId",
  "printMockupFingerprint" = "aiMockupFingerprint",
  "printMockupGeneratedAt" = "aiMockupGeneratedAt"
WHERE "aiMockupId" IN (SELECT "id" FROM "Mockup" WHERE "model" = 'print');

UPDATE "BuildDraft"
SET
  "aiMockupId" = NULL,
  "aiMockupFingerprint" = NULL,
  "aiMockupGeneratedAt" = NULL
WHERE "aiMockupId" IN (SELECT "id" FROM "Mockup" WHERE "model" = 'print');
